### ISSUE TITLE
[Question] Is this project abandoned?

### ISSUE THREAD

**Issue by alext-w** [Metamatrix/web-disability-simulator#4]
Just wanted to ask if this project is abandoned, or if any further development (or at least maintenance) is planned. For example, the jQuery being bundled is quite old and has security vulnerabilities (not sure how relevant to the browser plugin use case, but still).

If nothing is planned, what's your attitude towards contributions or maybe forks, to keep the project going?

**Comment by andreasnylin** [comment]
Hello @alext-w 
I'm affraid this project is abandoned and no further development is planned. I cannot answer your question about forks since I don't own the project.

**Comment by KaKi87** [comment]
Hi,
Did anyone find an alternative to this project that's also open source ?
Thanks
